import js from '@eslint/js';
import vue from 'eslint-plugin-vue';
import prettier from 'eslint-config-prettier';

export default [
  { ignores: ['dist/**', 'node_modules/**', 'public/**', '.vite/**', 'coverage/**'] },
  js.configs.recommended,
  ...vue.configs['flat/recommended'],
  prettier,
  {
    languageOptions: {
      globals: {
        node: true,
        process: true,
        console: true,
        document: true,
        window: true,
        localStorage: true,
        sessionStorage: true,
        setTimeout: true,
        clearTimeout: true,
        setInterval: true,
        clearInterval: true,
        alert: true,
        confirm: true,
        navigator: true,
        location: true,
        URL: true,
        Request: true,
        Response: true,
        Headers: true,
        File: true,
        FileReader: true,
        Image: true,
        XMLHttpRequest: true,
        MutationObserver: true,
        performance: true,
        module: true,
        indexedDB: true,
        getComputedStyle: true,
        HTMLElement: true,
        HTMLButtonElement: true,
        Node: true,
        Element: true,
        FetchEvent: true,
        URLSearchParams: true,
        XMLSerializer: true,
        importScripts: true,
        self: true,
        prompt: true,
        __dirname: true,
      },
    },
    rules: {
      'no-console': process.env.NODE_ENV === 'production' ? 'warn' : 'off',
      'no-debugger': process.env.NODE_ENV === 'production' ? 'warn' : 'off',
      'vue/multi-word-component-names': 'off',
    },
  },
];